sudo: false
language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-xh' ]; then cd .. && eval "mv $currentfolder generator-xh" && cd generator-xh; fi

